Repository ESP32Async/ESPAsyncWebServer, pull requests merged in 2025-02, with the labels that each got.

#45 fix(http): Status 404 should be returned by default when no notFoundHandler is set. This is not an internal server error.
  src/WebHandlers.cpp
Labels: Status: Pending Merge

#48 Add the option to add multiple headers with the same name
  README.md
  examples/Headers/Headers.ino
  src/ESPAsyncWebServer.h
  src/WebResponses.cpp
  src/literals.h
Labels: Status: Pending Merge

#55 doc(wiki): Moving doc to Wiki
  README.md
Labels: Type: Documentation, Status: Pending Merge

#51 fix(mem): Log an error when a memory allocation fails
  src/AsyncEventSource.cpp
  src/AsyncJson.cpp
  src/AsyncMessagePack.cpp
  src/AsyncWebHeader.cpp
  src/AsyncWebSocket.cpp
  src/Middleware.cpp
  src/WebAuthentication.cpp
  src/WebHandlers.cpp
  src/WebRequest.cpp
  src/WebResponses.cpp
  src/WebServer.cpp
Labels: Status: Pending Merge, Type: Improvement

#50 feat(http): Skipping Middleware
  examples/SkipServerMiddleware/SkipServerMiddleware.ino
  platformio.ini
  src/ESPAsyncWebServer.h
  src/WebRequest.cpp
  src/WebServer.cpp
Labels: Status: Pending Merge, Type: Feature

#41 feat(http) Request Continuation support
  examples/RequestContinuation/RequestContinuation.ino
  examples/RequestContinuationComplete/RequestContinuationComplete.ino
  platformio.ini
  src/ESPAsyncWebServer.h
  src/WebRequest.cpp
Labels: Status: Pending Merge, Type: Feature

#56 feat(http): Add ability to abort a request
  src/ESPAsyncWebServer.h
  src/WebRequest.cpp
Labels: Status: Pending Merge, Type: Feature

#61 AsyncTCP v3.3.4
  .github/workflows/build-arduino.yml
  library.json
  platformio.ini
Labels: Status: Pending Merge

#62 ESP32Async/AsyncTCP @ 3.3.5
  .github/workflows/build-arduino.yml
  library.json
  platformio.ini
Labels: Status: Pending Merge

#57 fix(mem): allocation checks and request abort on failed allocation
  examples/Auth/Auth.ino
  examples/CORS/CORS.ino
  examples/CatchAllHandler/CatchAllHandler.ino
  examples/ChunkResponse/ChunkResponse.ino
  examples/EndBegin/EndBegin.ino
  examples/Filters/Filters.ino
  examples/FlashResponse/FlashResponse.ino
  examples/HeaderManipulation/HeaderManipulation.ino
  examples/Json/Json.ino
  examples/Logging/Logging.ino
  examples/MessagePack/MessagePack.ino
  examples/Middleware/Middleware.ino
  examples/Params/Params.ino
  examples/RateLimit/RateLimit.ino
  examples/Redirect/Redirect.ino
  examples/ResumableDownload/ResumableDownload.ino
  examples/Rewrite/Rewrite.ino
  examples/SkipServerMiddleware/SkipServerMiddleware.ino
  examples/StaticFile/StaticFile.ino
  examples/Templates/Templates.ino
  src/AsyncEventSource.cpp
  src/AsyncJson.cpp
  src/AsyncMessagePack.cpp
  src/AsyncWebHeader.cpp
  src/AsyncWebSocket.cpp
  src/ESPAsyncWebServer.h
  src/Middleware.cpp
  src/WebAuthentication.cpp
  src/WebHandlers.cpp
  src/WebRequest.cpp
  src/WebResponses.cpp
  src/WebServer.cpp
Labels: Status: Pending Merge, Type: Improvement

#63 Add integration for IDF Component Manager
  .github/workflows/upload-idf-component.yml
  idf_component.yml
  idf_component_examples/catchall/CMakeLists.txt
  idf_component_examples/catchall/README.md
  idf_component_examples/catchall/main/CMakeLists.txt
  idf_component_examples/catchall/main/idf_component.yml
  idf_component_examples/catchall/main/main.cpp
  idf_component_examples/catchall/sdkconfig.defaults
  idf_component_examples/serversentevents/CMakeLists.txt
  idf_component_examples/serversentevents/README.md
  idf_component_examples/serversentevents/main/CMakeLists.txt
  idf_component_examples/serversentevents/main/idf_component.yml
  idf_component_examples/serversentevents/main/main.cpp
  idf_component_examples/serversentevents/sdkconfig.defaults
  idf_component_examples/websocket/CMakeLists.txt
  idf_component_examples/websocket/README.md
  idf_component_examples/websocket/main/CMakeLists.txt
  idf_component_examples/websocket/main/idf_component.yml
  idf_component_examples/websocket/main/main.cpp
  idf_component_examples/websocket/sdkconfig.defaults
Labels: Status: Pending Merge

#69 doc(example): pioarduino example with hybrid compilation to show how to increase the max sockets (CONFIG_LWIP_MAX_ACTIVE_TCP)
  pioarduino_examples/IncreaseMaxSockets/.gitignore
  pioarduino_examples/IncreaseMaxSockets/platformio.ini
  pioarduino_examples/IncreaseMaxSockets/src/main.cpp
Labels: Status: Pending Merge

#72 doc(examples): Added Upload example for text upload, binary upload and file upload
  examples/Upload/Upload.ino
  platformio.ini
Labels: Status: Pending Merge

#78 Add ArduinoJson as dependency for ESP-IDF
  idf_component.yml
Labels: Status: Pending Merge

#77 Arduino core 3.1.2 based on IDF 5.3.2.250210
  .github/workflows/build-arduino.yml
  pioarduino_examples/IncreaseMaxSockets/platformio.ini
  platformio.ini
Labels: Status: Pending Merge

#83 Arduino core 3.1.3 based on IDF 5.3.2.250210
  pioarduino_examples/IncreaseMaxSockets/platformio.ini
  platformio.ini
Labels: Status: Pending Merge

#84 Adding Serial.printf in WebSocket example
  examples/WebSocket/WebSocket.ino
Labels: Status: Pending Merge

#86 v3.7.1
  library.json
  library.properties
  src/AsyncWebServerVersion.h
Labels: Status: Pending Merge

#92 Fix CI
  .github/workflows/build-arduino.yml
  .github/workflows/build-pioarduino.yml
  platformio.ini
Labels: Status: Pending Merge

#94 Add CI for Arduino Pre-Release v3.2.0-RC1 based on ESP-IDF v5.4.0.250218
  .github/workflows/build-pioarduino.yml
  platformio.ini
Labels: Status: Pending Merge
